baseURL = "https://koobai.com"
languageCode = "zh-cn"
theme = "jingzhe_2"
themesDir = "themes"
title = "空白Koobai"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true
hasCJKLanguage = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[permalinks]
  posts = '/:slug/'

[params.artalk]
    server="https://c.koobai.com"
    site="Koobai 空白生活"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '唠叨'
    url = '/'
    weight = 1
    params = { umami_event = "Home" }
  [[menu.main]]
    identifier = "Goods"
    name = "店铺"
    url = "https://qiszy.taobao.com"
    weight = 6
    params = { new_window = true, umami_event = "Taobao" }